### ISSUE TITLE
Does not build with `--frozen`

### ISSUE THREAD

**Issue by piorrro33** [wwylele/save3ds#18]
I think `cargo.lock` needs to be updated. Running `cargo generate-lockfile` then `cargo fetch --locked` fixed the build for me.

```
error: failed to get `ahash` as a dependency of package `hashbrown v0.13.2`
    ... which satisfies dependency `hashbrown = "^0.13"` (locked to 0.13.2) of package `lru v0.10.0`
    ... which satisfies dependency `lru = "^0.10"` (locked to 0.10.0) of package `libsave3ds v0.1.0 (/home/pierre/archlinux-packages/AUR/save3ds_fuse-git/src/save3ds/libsave3ds)`
    ... which satisfies path dependency `libsave3ds` (locked to 0.1.0) of package `save3ds_fuse v0.1.0 (/home/pierre/archlinux-packages/AUR/save3ds_fuse-git/src/save3ds/save3ds_fuse)`

Caused by:
  attempting to make an HTTP request, but --frozen was specified
```

**Comment by wwylele** [comment]
This is strange, because yesterday I did exactly updating dependencies together with `cargo.lock` file (you can check the commit history), and the mentioned `ahash` package is there. 

Did your local `cargo.lock` file content change after the fix you did? If so, could you PR the change?

**Comment by HarmfulBreeze** [comment]
Hey, thank you for your response. I'm the maintainer of the AUR package `save3ds_fuse-git`; I went ahead and did more debugging, and it turns out the package can be built from my system as long as I don't `export RUSTUP_TOOLCHAIN=stable`, and in a clean chroot.

So it was just a matter of running `rustup update`, and the build was fixed. Sorry for that!
